In [1]:
import nltk

In [2]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Axel\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [3]:
#nltk.download()
#nltk.download('punkt')

In [4]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.tokenize import RegexpTokenizer
import numpy as np    
from numpy import dot
from numpy.linalg import norm

In [5]:
stopwords.fileids()

['arabic',
 'azerbaijani',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'greek',
 'hungarian',
 'indonesian',
 'italian',
 'kazakh',
 'nepali',
 'norwegian',
 'portuguese',
 'romanian',
 'russian',
 'slovene',
 'spanish',
 'swedish',
 'tajik',
 'turkish']

In [7]:
set(stopwords.words('english'))


{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [8]:
set(stopwords.words('spanish'))


{'a',
 'al',
 'algo',
 'algunas',
 'algunos',
 'ante',
 'antes',
 'como',
 'con',
 'contra',
 'cual',
 'cuando',
 'de',
 'del',
 'desde',
 'donde',
 'durante',
 'e',
 'el',
 'ella',
 'ellas',
 'ellos',
 'en',
 'entre',
 'era',
 'erais',
 'eran',
 'eras',
 'eres',
 'es',
 'esa',
 'esas',
 'ese',
 'eso',
 'esos',
 'esta',
 'estaba',
 'estabais',
 'estaban',
 'estabas',
 'estad',
 'estada',
 'estadas',
 'estado',
 'estados',
 'estamos',
 'estando',
 'estar',
 'estaremos',
 'estará',
 'estarán',
 'estarás',
 'estaré',
 'estaréis',
 'estaría',
 'estaríais',
 'estaríamos',
 'estarían',
 'estarías',
 'estas',
 'este',
 'estemos',
 'esto',
 'estos',
 'estoy',
 'estuve',
 'estuviera',
 'estuvierais',
 'estuvieran',
 'estuvieras',
 'estuvieron',
 'estuviese',
 'estuvieseis',
 'estuviesen',
 'estuvieses',
 'estuvimos',
 'estuviste',
 'estuvisteis',
 'estuviéramos',
 'estuviésemos',
 'estuvo',
 'está',
 'estábamos',
 'estáis',
 'están',
 'estás',
 'esté',
 'estéis',
 'estén',
 'estés',
 'fue',
 'f

In [9]:
tokenizer = RegexpTokenizer(r'\w+')


In [10]:
#Párrafo 1
text_01 = "Se dispara el coronavirus: la cifra de muertos aumenta 242 en la provincia de Hubei, mientras que la cifra mundial de muertes por coronavirus aumenta a 1.357"

In [11]:
#Párrafo 2
text_02 ="The 2020 #ChineseGP will be postponed due to the coronavirus outbreak F1 and the FIA have accepted a request from the promoter to postpone the event We will continue to monitor the situation and assess potential alternative dates"

In [19]:
#Párrafo 3
text_03 ="Crea @UNAM_MX Licenciatura en Ingeniería Aeroespacial Se impartirá en la Facultad de Ingeniería, en Ciudad Universitaria, donde los alumnos deberán cursar 10 semestres y cubrir 450 créditos."

In [13]:
#Párrafo 4
text_04 ="Samsung Galaxy Z Flip cuenta con una pantalla protegida por vidrio ultra fino, tiene una pequeña pantalla en el exterior que muestra la hora o quién te llama y lo más importante: permite hacer selfies sin tocar ningún botón."

In [14]:
#Parrafo 5
text_05 ="Llegó el 2020 y nos encontramos con una serie de estrenos que nos harán iniciar a lo grande. Sin lugar a dudas, el regreso de Cloud, Tifa y Aerith en Final Fantasy VII Remake, no se trata solamente de uno de los juegos más esperados del año, sino más bien de la década"

In [ ]:
TOKENIZAR

In [15]:
text_01_tokens = tokenizer.tokenize(text_01.lower()) #tokenizar y quitar signos de puntuación
#print(text_01_tokens)

text_01_tokens_wout_stopwords = []

for word in text_01_tokens:
    if word not in stopwords.words('spanish'): text_01_tokens_wout_stopwords.append(word)

print(text_01_tokens_wout_stopwords)

['dispara', 'coronavirus', 'cifra', 'muertos', 'aumenta', '242', 'provincia', 'hubei', 'mientras', 'cifra', 'mundial', 'muertes', 'coronavirus', 'aumenta', '1', '357']


In [17]:
text_02_tokens = tokenizer.tokenize(text_02.lower()) #tokenizar y quitar signos de puntuación
#print(text_02_tokens)

text_02_tokens_wout_stopwords = []

for word in text_02_tokens:
    if word not in stopwords.words('english'): text_02_tokens_wout_stopwords.append(word)

print(text_02_tokens_wout_stopwords)

['2020', 'chinesegp', 'postponed', 'due', 'coronavirus', 'outbreak', 'f1', 'fia', 'accepted', 'request', 'promoter', 'postpone', 'event', 'continue', 'monitor', 'situation', 'assess', 'potential', 'alternative', 'dates']


In [20]:
text_03_tokens = tokenizer.tokenize(text_03.lower()) 
#print(text_03_tokens)

text_03_tokens_wout_stopwords = []

for word in text_03_tokens:
    if word not in stopwords.words('spanish'): text_03_tokens_wout_stopwords.append(word)

print(text_03_tokens_wout_stopwords)

['crea', 'unam_mx', 'licenciatura', 'ingeniería', 'aeroespacial', 'impartirá', 'facultad', 'ingeniería', 'ciudad', 'universitaria', 'alumnos', 'deberán', 'cursar', '10', 'semestres', 'cubrir', '450', 'créditos']


In [21]:
text_04_tokens = tokenizer.tokenize(text_03.lower()) 
#print(text_04_tokens)

text_04_tokens_wout_stopwords = []

for word in text_04_tokens:
    if word not in stopwords.words('spanish'): text_04_tokens_wout_stopwords.append(word)

print(text_04_tokens_wout_stopwords)

['crea', 'unam_mx', 'licenciatura', 'ingeniería', 'aeroespacial', 'impartirá', 'facultad', 'ingeniería', 'ciudad', 'universitaria', 'alumnos', 'deberán', 'cursar', '10', 'semestres', 'cubrir', '450', 'créditos']


In [22]:
text_05_tokens = tokenizer.tokenize(text_05.lower()) 
#print(text_05_tokens)

text_05_tokens_wout_stopwords = []

for word in text_05_tokens:
    if word not in stopwords.words('spanish'): text_05_tokens_wout_stopwords.append(word)

print(text_05_tokens_wout_stopwords)

['llegó', '2020', 'encontramos', 'serie', 'estrenos', 'harán', 'iniciar', 'grande', 'lugar', 'dudas', 'regreso', 'cloud', 'tifa', 'aerith', 'final', 'fantasy', 'vii', 'remake', 'trata', 'solamente', 'juegos', 'esperados', 'año', 'sino', 'bien', 'década']


In [23]:
print(len(text_01_tokens_wout_stopwords))
print(len(text_02_tokens_wout_stopwords))
print(len(text_03_tokens_wout_stopwords))
print(len(text_04_tokens_wout_stopwords))
print(len(text_05_tokens_wout_stopwords))
print(len(text_01_tokens_wout_stopwords) + len(text_02_tokens_wout_stopwords) + len(text_03_tokens_wout_stopwords)+len(text_04_tokens_wout_stopwords)+len(text_05_tokens_wout_stopwords))

16
20
18
18
26
98


BoW

In [24]:
dicc_texts = {"text_01": text_01_tokens_wout_stopwords, 
              "text_02": text_02_tokens_wout_stopwords, 
              "text_03": text_03_tokens_wout_stopwords,
              "text_04": text_04_tokens_wout_stopwords,
              "text_05": text_05_tokens_wout_stopwords,}
#dicc_texts

In [25]:
dicc_termns = {}

for text in dicc_texts:
    for word in dicc_texts[text]:
        
#        print("EVALUAR:", word, "EN", text)
        
        if(word in dicc_termns):#incrementar palabras al diccionario
            dicc_termns[word] = dicc_termns[word] + 1
            
#            print(word, "IN", "dicc_termns")
            
        elif(word not in dicc_termns):#agregar palabras al diccionario        
            dicc_termns[word] = 1
            
#            print(word, "NOT IN", "dicc_termns")            

print(len(dicc_termns))
dicc_termns

74


{'dispara': 1,
 'coronavirus': 3,
 'cifra': 2,
 'muertos': 1,
 'aumenta': 2,
 '242': 1,
 'provincia': 1,
 'hubei': 1,
 'mientras': 1,
 'mundial': 1,
 'muertes': 1,
 '1': 1,
 '357': 1,
 '2020': 2,
 'chinesegp': 1,
 'postponed': 1,
 'due': 1,
 'outbreak': 1,
 'f1': 1,
 'fia': 1,
 'accepted': 1,
 'request': 1,
 'promoter': 1,
 'postpone': 1,
 'event': 1,
 'continue': 1,
 'monitor': 1,
 'situation': 1,
 'assess': 1,
 'potential': 1,
 'alternative': 1,
 'dates': 1,
 'crea': 2,
 'unam_mx': 2,
 'licenciatura': 2,
 'ingeniería': 4,
 'aeroespacial': 2,
 'impartirá': 2,
 'facultad': 2,
 'ciudad': 2,
 'universitaria': 2,
 'alumnos': 2,
 'deberán': 2,
 'cursar': 2,
 '10': 2,
 'semestres': 2,
 'cubrir': 2,
 '450': 2,
 'créditos': 2,
 'llegó': 1,
 'encontramos': 1,
 'serie': 1,
 'estrenos': 1,
 'harán': 1,
 'iniciar': 1,
 'grande': 1,
 'lugar': 1,
 'dudas': 1,
 'regreso': 1,
 'cloud': 1,
 'tifa': 1,
 'aerith': 1,
 'final': 1,
 'fantasy': 1,
 'vii': 1,
 'remake': 1,
 'trata': 1,
 'solamente': 1,
 'ju

In [26]:
matrix = np.zeros((len(dicc_texts), len(dicc_termns))) # Pre-allocate matrix
#matrix

In [27]:
i = 0
j = 0

for word_termns in dicc_termns: #dicc_termns todos los términos
#    print()
    for word_texts in dicc_texts: #dicc_texts todos los textos
#        print("EVALUAR:", word_termns, "EN: ", word_texts)
        if(word_termns in dicc_texts[word_texts]): #si está
            print(word_termns, "IN", word_texts)
            
            matrix[j, i] = 1
            
        elif(word_termns not in dicc_texts[word_texts]): # si no está
            print(word_termns, "NOT IN", word_texts)
            
            matrix[j, i] = 0
            
            
        print("se agregó: ", matrix[j,i], "en: ", j, i)
            
        j = j + 1
        
    j = 0
    i = i + 1

dispara IN text_01
se agregó:  1.0 en:  0 0
dispara NOT IN text_02
se agregó:  0.0 en:  1 0
dispara NOT IN text_03
se agregó:  0.0 en:  2 0
dispara NOT IN text_04
se agregó:  0.0 en:  3 0
dispara NOT IN text_05
se agregó:  0.0 en:  4 0
coronavirus IN text_01
se agregó:  1.0 en:  0 1
coronavirus IN text_02
se agregó:  1.0 en:  1 1
coronavirus NOT IN text_03
se agregó:  0.0 en:  2 1
coronavirus NOT IN text_04
se agregó:  0.0 en:  3 1
coronavirus NOT IN text_05
se agregó:  0.0 en:  4 1
cifra IN text_01
se agregó:  1.0 en:  0 2
cifra NOT IN text_02
se agregó:  0.0 en:  1 2
cifra NOT IN text_03
se agregó:  0.0 en:  2 2
cifra NOT IN text_04
se agregó:  0.0 en:  3 2
cifra NOT IN text_05
se agregó:  0.0 en:  4 2
muertos IN text_01
se agregó:  1.0 en:  0 3
muertos NOT IN text_02
se agregó:  0.0 en:  1 3
muertos NOT IN text_03
se agregó:  0.0 en:  2 3
muertos NOT IN text_04
se agregó:  0.0 en:  3 3
muertos NOT IN text_05
se agregó:  0.0 en:  4 3
aumenta IN text_01
se agregó:  1.0 en:  0 4
aument

se agregó:  0.0 en:  0 49
llegó NOT IN text_02
se agregó:  0.0 en:  1 49
llegó NOT IN text_03
se agregó:  0.0 en:  2 49
llegó NOT IN text_04
se agregó:  0.0 en:  3 49
llegó IN text_05
se agregó:  1.0 en:  4 49
encontramos NOT IN text_01
se agregó:  0.0 en:  0 50
encontramos NOT IN text_02
se agregó:  0.0 en:  1 50
encontramos NOT IN text_03
se agregó:  0.0 en:  2 50
encontramos NOT IN text_04
se agregó:  0.0 en:  3 50
encontramos IN text_05
se agregó:  1.0 en:  4 50
serie NOT IN text_01
se agregó:  0.0 en:  0 51
serie NOT IN text_02
se agregó:  0.0 en:  1 51
serie NOT IN text_03
se agregó:  0.0 en:  2 51
serie NOT IN text_04
se agregó:  0.0 en:  3 51
serie IN text_05
se agregó:  1.0 en:  4 51
estrenos NOT IN text_01
se agregó:  0.0 en:  0 52
estrenos NOT IN text_02
se agregó:  0.0 en:  1 52
estrenos NOT IN text_03
se agregó:  0.0 en:  2 52
estrenos NOT IN text_04
se agregó:  0.0 en:  3 52
estrenos IN text_05
se agregó:  1.0 en:  4 52
harán NOT IN text_01
se agregó:  0.0 en:  0 53
harán

In [28]:
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

In [29]:
matrix.shape

(5, 74)

In [30]:
matrix[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [31]:
matrix[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [32]:
matrix[2]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [33]:
matrix[3]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [34]:
matrix[4]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [35]:
matrix[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [36]:
bin_cos_t01_t02 = dot(matrix[0],matrix[1])/(norm(matrix[0])*norm(matrix[1]))
bin_cos_t01_t02

0.062017367294604234

In [37]:
bin_cos_t01_t03 = dot(matrix[0],matrix[2])/(norm(matrix[0])*norm(matrix[2]))
bin_cos_t01_t03

0.0

In [38]:
bin_cos_t01_t04 = dot(matrix[0],matrix[3])/(norm(matrix[0])*norm(matrix[3]))
bin_cos_t01_t04

0.0

In [39]:
bin_cos_t01_t05 = dot(matrix[0],matrix[4])/(norm(matrix[0])*norm(matrix[4]))
bin_cos_t01_t05

0.0

In [40]:
bin_cos_t02_t03 = dot(matrix[1],matrix[2])/(norm(matrix[1])*norm(matrix[2]))
bin_cos_t02_t03

0.0

In [41]:
bin_cos_t02_t04 = dot(matrix[1],matrix[3])/(norm(matrix[1])*norm(matrix[3]))
bin_cos_t02_t04

0.0

In [42]:
bin_cos_t02_t05 = dot(matrix[1],matrix[4])/(norm(matrix[1])*norm(matrix[4]))
bin_cos_t02_t05

0.043852900965351466

In [43]:
bin_cos_t03_t04 = dot(matrix[2],matrix[3])/(norm(matrix[2])*norm(matrix[3]))
bin_cos_t03_t04

1.0

In [44]:
bin_cos_t03_t05 = dot(matrix[2],matrix[4])/(norm(matrix[2])*norm(matrix[4]))
bin_cos_t03_t05

0.0

In [45]:
bin_cos_t04_t05 = dot(matrix[3],matrix[4])/(norm(matrix[3])*norm(matrix[4]))
bin_cos_t04_t05

0.0

Matriz termino documento con frecuencia

In [46]:
matrix = np.zeros((len(dicc_texts), len(dicc_termns))) # Pre-allocate matrix
#matrix

In [47]:
i = 0
j = 0

for word_termns in dicc_termns: #dicc_termns todos los términos
#    print()
    for word_texts in dicc_texts: #dicc_texts todos los textos
#        print("EVALUAR:", word_termns, "EN: ", word_texts)
        if(word_termns in dicc_texts[word_texts]): #si está
            print(word_termns, "IN", word_texts)
            
            matrix[j, i] = dicc_termns[word_termns]
            
        elif(word_termns not in dicc_texts[word_texts]): # si no está
            print(word_termns, "NOT IN", word_texts)
            
            matrix[j, i] = 0
            
            
        print("se agregó: ", matrix[j,i], "en: ", j, i)
            
        j = j + 1
        
    j = 0
    i = i + 1

dispara IN text_01
se agregó:  1.0 en:  0 0
dispara NOT IN text_02
se agregó:  0.0 en:  1 0
dispara NOT IN text_03
se agregó:  0.0 en:  2 0
dispara NOT IN text_04
se agregó:  0.0 en:  3 0
dispara NOT IN text_05
se agregó:  0.0 en:  4 0
coronavirus IN text_01
se agregó:  3.0 en:  0 1
coronavirus IN text_02
se agregó:  3.0 en:  1 1
coronavirus NOT IN text_03
se agregó:  0.0 en:  2 1
coronavirus NOT IN text_04
se agregó:  0.0 en:  3 1
coronavirus NOT IN text_05
se agregó:  0.0 en:  4 1
cifra IN text_01
se agregó:  2.0 en:  0 2
cifra NOT IN text_02
se agregó:  0.0 en:  1 2
cifra NOT IN text_03
se agregó:  0.0 en:  2 2
cifra NOT IN text_04
se agregó:  0.0 en:  3 2
cifra NOT IN text_05
se agregó:  0.0 en:  4 2
muertos IN text_01
se agregó:  1.0 en:  0 3
muertos NOT IN text_02
se agregó:  0.0 en:  1 3
muertos NOT IN text_03
se agregó:  0.0 en:  2 3
muertos NOT IN text_04
se agregó:  0.0 en:  3 3
muertos NOT IN text_05
se agregó:  0.0 en:  4 3
aumenta IN text_01
se agregó:  2.0 en:  0 4
aument

encontramos NOT IN text_03
se agregó:  0.0 en:  2 50
encontramos NOT IN text_04
se agregó:  0.0 en:  3 50
encontramos IN text_05
se agregó:  1.0 en:  4 50
serie NOT IN text_01
se agregó:  0.0 en:  0 51
serie NOT IN text_02
se agregó:  0.0 en:  1 51
serie NOT IN text_03
se agregó:  0.0 en:  2 51
serie NOT IN text_04
se agregó:  0.0 en:  3 51
serie IN text_05
se agregó:  1.0 en:  4 51
estrenos NOT IN text_01
se agregó:  0.0 en:  0 52
estrenos NOT IN text_02
se agregó:  0.0 en:  1 52
estrenos NOT IN text_03
se agregó:  0.0 en:  2 52
estrenos NOT IN text_04
se agregó:  0.0 en:  3 52
estrenos IN text_05
se agregó:  1.0 en:  4 52
harán NOT IN text_01
se agregó:  0.0 en:  0 53
harán NOT IN text_02
se agregó:  0.0 en:  1 53
harán NOT IN text_03
se agregó:  0.0 en:  2 53
harán NOT IN text_04
se agregó:  0.0 en:  3 53
harán IN text_05
se agregó:  1.0 en:  4 53
iniciar NOT IN text_01
se agregó:  0.0 en:  0 54
iniciar NOT IN text_02
se agregó:  0.0 en:  1 54
iniciar NOT IN text_03
se agregó:  0.0 

In [48]:
matrix

array([[1., 3., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        2., 2., 2., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

In [49]:
matrix.shape

(5, 74)

In [50]:
    matrix[0]

array([1., 3., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [51]:
matrix[1]

array([0., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [52]:
matrix[2]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2.,
       2., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [53]:
matrix[3]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2.,
       2., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [54]:
matrix[4]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [55]:
matrix[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [56]:
df_cos_t01_t02 = dot(matrix[0],matrix[1])/(norm(matrix[0])*norm(matrix[1]))
df_cos_t01_t02

0.3110855084191276

In [57]:
df_cos_t01_t03 = dot(matrix[0],matrix[2])/(norm(matrix[0])*norm(matrix[2]))
df_cos_t01_t03

0.0

In [58]:
df_cos_t01_t04 = dot(matrix[0],matrix[3])/(norm(matrix[0])*norm(matrix[3]))
df_cos_t01_t04

0.0

In [59]:
df_cos_t01_t05 = dot(matrix[0],matrix[4])/(norm(matrix[0])*norm(matrix[4]))
df_cos_t01_t05

0.0

In [60]:
df_cos_t02_t03 = dot(matrix[1],matrix[2])/(norm(matrix[1])*norm(matrix[2]))
df_cos_t02_t03

0.0

In [61]:
df_cos_t02_t04 = dot(matrix[1],matrix[3])/(norm(matrix[1])*norm(matrix[3]))
df_cos_t02_t04

0.0

In [62]:
df_cos_t02_t05 = dot(matrix[1],matrix[4])/(norm(matrix[1])*norm(matrix[4]))
df_cos_t02_t05

0.13340746919301402

In [63]:
df_cos_t03_t04 = dot(matrix[2],matrix[3])/(norm(matrix[2])*norm(matrix[3]))
df_cos_t03_t04

0.9999999999999998

In [64]:
df_cos_t03_t05 = dot(matrix[2],matrix[4])/(norm(matrix[2])*norm(matrix[4]))
df_cos_t03_t05

0.0

In [65]:
df_cos_t04_t05 = dot(matrix[3],matrix[4])/(norm(matrix[3])*norm(matrix[4]))
df_cos_t04_t05

0.0